#https://hub.docker.com/_/microsoft-dotnet-core-sdk/
FROM mcr.microsoft.com/dotnet/sdk:5.0.100-alpine3.12

# Add dependencies for Timezone support;
RUN apk add --no-cache tzdata

ENV \
    #Disable telemety
    DOTNET_CLI_TELEMETRY_OPTOUT=1