FROM node:12.18.3-stretch
RUN \
    mkdir /sass && \
    cd /sass && \
    wget https://github.com/sass/node-sass/releases/download/v4.14.1/linux-x64-83_binding.node && \
    wget https://github.com/sass/node-sass/releases/download/v4.14.1/linux-x64-79_binding.node && \
    wget https://github.com/sass/node-sass/releases/download/v4.14.1/linux-x64-72_binding.node && \
    wget https://github.com/sass/node-sass/releases/download/v4.14.1/linux-x64-67_binding.node

ENV SASS_BINARY_DIR=/sass