FROM node:12.18.3-stretch
RUN \
    mkdir -p /root/.npm/_cacache/node-sass/4.14.1 && \
    cd /root/.npm/_cacache/node-sass/4.14.1 && \
    wget https://github.com/sass/node-sass/releases/download/v4.14.1/linux-x64-83_binding.node && \
    wget https://github.com/sass/node-sass/releases/download/v4.14.1/linux-x64-79_binding.node