#https://hub.docker.com/_/microsoft-dotnet-aspnet/
FROM mcr.microsoft.com/dotnet/aspnet:5.0.7-buster-slim-amd64
ENV \
    # Configure web servers to bind to port 80 when present
    ASPNETCORE_URLS=http://+:80 \
    # Disable telemety
    DOTNET_CLI_TELEMETRY_OPTOUT=1 \
    # Set TZ
    TZ=Europe/Moscow \
    # Enable X-Forwarded
    ASPNETCORE_FORWARDEDHEADERS_ENABLED=true \
    # Set locale
    LC_ALL=C.UTF-8

